Witty\UserBundle\Entity\User:
    type: entity
    repositoryClass: Witty\UserBundle\Repository\UserRepository
    table: user
    oneToMany:
        shares:
            targetEntity: Witty\ShareBundle\Entity\Share
            mappedBy: user
        userRewards:
            targetEntity: Witty\ProjectBundle\Entity\UserReward
            mappedBy: user
        projects:
            targetEntity: Witty\ProjectBundle\Entity\Project
            mappedBy: creator
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        login:
            type: string
            length: 64
            fixed: false
            nullable: true
        firstname:
            type: string
            length: 31
            fixed: false
            nullable: true
        lastname:
            type: string
            length: 31
            fixed: false
            nullable: true
        address:
            type: string
            length: 255
            fixed: false
            nullable: true
        address2:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: address_2
        city:
            type: string
            length: 63
            fixed: false
            nullable: true
        postcode:
            type: string
            length: 5
            fixed: false
            nullable: true
        description:
            type: text
            nullable: true
        balance:
            type: decimal
            nullable: true
        sex:
            type: boolean
            nullable: true
        avatar:
            type: string
            length: 255
            fixed: false
            nullable: true
        activationCode:
            type: string
            length: 32
            fixed: false
            nullable: true
            column: activation_code
        birthdate:
            type: datetime
            nullable: true
        isEditor:
            type: boolean
            nullable: true
            column: is_editor
        isAuthor:
            type: boolean
            nullable: true
            column: is_author
        defaultLocale:
            type: string
            length: 2
            fixed: false
            nullable: true
            column: default_locale
        country:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: country
        loginDp:
            type: string
            length: 16
            fixed: false
            nullable: true
            column: login_dp
        passwordDp:
            type: string
            length: 16
            fixed: false
            nullable: true
            column: password_dp
        origine:
            type: boolean
            nullable: true
        old_password:
            type: string
            length: 255
            fixed: false
            nullable: true
        newsletter:
            type: boolean
            nullable: true
        phone:
            type: string
            length: 20
            fixed: false
            nullable: true
        facebookId:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: facebook_id
    lifecycleCallbacks: 
        prePersist: [ preUpload ]
        preUpdate: [ preUpload ]

