PhpbbConfig:
    type: entity
    table: phpbb_config
    fields:
        configName:
            id: true
            type: string
            length: 255
            fixed: false
            nullable: false
            column: config_name
            generator:
                strategy: IDENTITY
        configValue:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: config_value
        isDynamic:
            type: boolean
            nullable: false
            column: is_dynamic
    lifecycleCallbacks: {  }
