ProductLink:
    type: entity
    table: product_link
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        productId:
            type: integer
            unsigned: false
            nullable: true
            column: product_id
        linkId:
            type: integer
            unsigned: false
            nullable: false
            column: link_id
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            column: updated_at
    lifecycleCallbacks: {  }
