ProductPackEntry:
    type: entity
    table: product_pack_entry
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            column: updated_at
        productPackId:
            type: integer
            unsigned: false
            nullable: false
            column: product_pack_id
        productId:
            type: integer
            unsigned: false
            nullable: false
            column: product_id
        productVersionId:
            type: integer
            unsigned: false
            nullable: false
            column: product_version_id
        quantity:
            type: integer
            unsigned: false
            nullable: false
    lifecycleCallbacks: {  }
