ProductPicture:
    type: entity
    table: product_picture
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        productId:
            type: integer
            unsigned: false
            nullable: true
            column: product_id
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            column: updated_at
        url:
            type: string
            length: 255
            fixed: false
            nullable: false
        title:
            type: string
            length: 255
            fixed: false
            nullable: false
        description:
            type: text
            nullable: false
    lifecycleCallbacks: {  }
