ProductCat:
    type: entity
    table: product_cat
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 50
            fixed: false
            nullable: false
        slug:
            type: string
            length: 255
            fixed: false
            nullable: false
        parentId:
            type: integer
            unsigned: false
            nullable: true
            column: parent_id
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            column: updated_at
    lifecycleCallbacks: {  }
