ProductPack:
    type: entity
    table: product_pack
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            column: updated_at
        name:
            type: string
            length: 255
            fixed: false
            nullable: false
        slug:
            type: string
            length: 255
            fixed: false
            nullable: false
        ref:
            type: string
            length: 64
            fixed: false
            nullable: false
        catchPhrase:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: catch_phrase
        shortDescription:
            type: text
            nullable: false
            column: short_description
        isPublish:
            type: boolean
            nullable: false
            column: is_publish
    lifecycleCallbacks: {  }
