ProductOptionChoice:
    type: entity
    table: product_option_choice
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        productOptionId:
            type: integer
            unsigned: false
            nullable: false
            column: product_option_id
        name:
            type: string
            length: 64
            fixed: false
            nullable: false
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            column: updated_at
    lifecycleCallbacks: {  }
