ProductPromo:
    type: entity
    table: product_promo
    fields:
        id:
            id: true
            type: integer
            unsigned: true
            nullable: false
            generator:
                strategy: IDENTITY
        productId:
            type: integer
            unsigned: false
            nullable: false
            column: product_id
        value:
            type: decimal
            nullable: false
        type:
            type: integer
            unsigned: false
            nullable: false
        dateBegin:
            type: datetime
            nullable: false
            column: date_begin
        dateEnd:
            type: datetime
            nullable: false
            column: date_end
        isUnique:
            type: boolean
            nullable: true
            column: is_unique
        isUse:
            type: boolean
            nullable: true
            column: is_use
        isShop:
            type: boolean
            nullable: false
            column: is_shop
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            column: updated_at
    lifecycleCallbacks: {  }
