PsConfiguration:
    type: entity
    table: ps_configuration
    fields:
        idConfiguration:
            id: true
            type: integer
            unsigned: true
            nullable: false
            column: id_configuration
            generator:
                strategy: IDENTITY
        idShopGroup:
            type: integer
            unsigned: true
            nullable: true
            column: id_shop_group
        idShop:
            type: integer
            unsigned: true
            nullable: true
            column: id_shop
        name:
            type: string
            length: 32
            fixed: false
            nullable: false
        value:
            type: text
            nullable: true
        dateAdd:
            type: datetime
            nullable: false
            column: date_add
        dateUpd:
            type: datetime
            nullable: false
            column: date_upd
    lifecycleCallbacks: {  }
