parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: witty_dev
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: contact@mywittygames.com
    mailer_password: null
    locale: fr
    secret: 5af99ad00cc4fc1389f9fbb4349f7c347c93448b
    database_path: null

#Urls des sites Witty
    witty.url_mwg: http://www.mywittygames.com/
    witty.url_mwn: http://www.mywittynews.com/
    witty.url_mws: http://www.mywittyshop.com/
    
#Paramètres des services
    witty.s3.bucket: mywittygames
    witty.s3.endpoint: https://s3-eu-west-1.amazonaws.com/mywittygames/
    witty.s3.options: 
        key: AKIAICH4QGFKNEHOOZAA
        secret: 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
        
    witty.paypal.url: https://www.paypal.com/cgi-bin/webscr
    witty.paypal.fees: 0.03
    witty.paypal.email_business: mywittygames@gmail.com