parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: witty_dev
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 5af99ad00cc4fc1389f9fbb4349f7c347c93448b
    database_path: null
