parameters:
    witty.fs.class: Witty\ToolsBundle\Model\Filesystem
    witty.s3.adapter.class: Witty\ToolsBundle\Service\Adapter\AmazonS3Adapter
    witty.s3.class: AmazonS3
    witty.s3.options: 
        key: AKIAICH4QGFKNEHOOZAA
        secret: 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
    witty.s3.bucket: mywittygames
    witty.s3.endpoint: https://s3-eu-west-1.amazonaws.com/mywittygames/
    witty.url_manager.class: Witty\ToolsBundle\Service\Twig\Extension\UrlManager