<?php

namespace Witty\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    public function findAllOrderedByCreationDate()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT p FROM WittyBlogBundle:Post p ORDER BY p.creationDate DESC')
            ->getResult();
    }
}
