<?php

namespace Witty\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    public function findAllOrderedByCreationDate()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT p FROM WittyBlogBundle:Post p ORDER BY p.creationDate DESC')
            ->getResult();
    }
	
    public function findLastPost()
    {
        return $this->findByNumber(1);
    }	
	
    public function countAll()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT count(p) FROM WittyBlogBundle:Post p')
            ->getSingleScalarResult();
    }	
	
    public function findByNumber($number)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT p FROM WittyBlogBundle:Post p ORDER BY p.creationDate DESC')
			->setMaxResults(1)
			->setFirstResult($number - 1)
            ->getSingleResult();
    }
}
