UserRewards:
    type: entity
    table: user_rewards
    fields:
        id:
            id: true
            type: bigint
            nullable: false
            generator:
                strategy: IDENTITY
    manyToOne:
        user:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
        reward:
            targetEntity: Rewards
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                reward_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
