project_accueil:
    pattern:   /
    defaults:  { _controller: WittyProjectBundle:Project:index }

project_display:
    pattern:   /{id}
    defaults:  { _controller: WittyProjectBundle:Project:display }