project_accueil:
    pattern:   /
    defaults:  { _controller: WittyProjectBundle:Project:index }

project_display:
    pattern:   /{slug}
    defaults:  { _controller: WittyProjectBundle:Project:display }
    
project_confirmation:
    pattern:   /soutien/{id}
    defaults:  { _controller: WittyProjectBundle:Project:confirmation }
    requirements:
        page:  \d+