UserTransaction:
    type: entity
    table: user_transaction
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        userId:
            type: integer
            unsigned: false
            nullable: true
            column: user_id
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            column: updated_at
        email:
            type: string
            length: 31
            fixed: false
            nullable: true
        firstname:
            type: string
            length: 31
            fixed: false
            nullable: true
        lastname:
            type: string
            length: 31
            fixed: false
            nullable: true
        address:
            type: string
            length: 255
            fixed: false
            nullable: true
        city:
            type: string
            length: 255
            fixed: false
            nullable: true
        postcode:
            type: string
            length: 255
            fixed: false
            nullable: true
        country:
            type: string
            length: 255
            fixed: false
            nullable: true
        amount:
            type: decimal
            nullable: true
        currency:
            type: string
            length: 3
            fixed: false
            nullable: true
        error:
            type: text
            nullable: true
        transactionId:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: transaction_id
        paymentStatus:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: payment_status
        fees:
            type: decimal
            nullable: true
        type:
            type: integer
            unsigned: false
            nullable: false
    lifecycleCallbacks: {  }
